version: '3.8'

services:
  app:
    build: .
    container_name: udemy-clone-app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - udemy-clone-network

  nginx:
    image: nginx:stable-alpine
    container_name: udemy-clone-nginx
    restart: unless-stopped
    ports:
      - "3010:80"
      # - "443:443" # Décommentez pour HTTPS et ajoutez la configuration SSL dans nginx.conf
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public:ro # Monte le répertoire public pour les assets statiques
    depends_on:
      - app
    networks:
      - udemy-clone-network

networks:
  udemy-clone-network:
    driver: bridge